var api = [
  [
    {
      name: "4-nin wa Sorezore Uso wo Tsuku",
      studio: "Studio Flad",
      image: "./images/1.jpg",
      date: "October 2022",
      pop: "",
      source: "Source • Manga",
      story:
        "Each girl has at least one secret. Rikka, Chiyo, Sekine, and Tsubasa are four good friends in the same class. But each one has a ridiculous secrets...!?",
      genra: ["comedy", "sci-fi"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "4ウソ",
      video: "https://youtu.be/6KPCyMQ5oNg",
    },
    {
      name: "Akiba Maid Sensou",
      studio: "P.A. Works",
      image: "./images/2.jpg",
      date: "October 7, 2022",
      pop: "",
      source: "Source • Original",
      story: "",
      genra: ["", ""],
      color: ["#8A2C0F"],
      flip: "アキバ冥途戦争",
      video: "https://youtu.be/ULfNBIsHgMw",
    },
    {
      name: "Akuyaku Reijou nano de Last Boss wo Kattemimashita",
      studio: "Maho Film",
      image: "./images/3.jpg",
      date: "October 2022",
      pop: "14",
      source: "Source • Original",
      story:
        "When Aileen, the Duke's daughter, regains her memories of her past life, she realizes she's barreling toward ruin at full speed. Searching for any way out of her hopeless situation, the method she chooses is to capture the heart of the last boss--the Demon Lord Claude!",
      genra: ["comedy", "fantasy"],
      color: ["#9263E9"],
      flip: "悪ラス",
      video: "https://youtu.be/5cfNLZqPBiM",
    },
    {
      name: "BLEACH: Sennen Kessen-hen",
      studio: "Studio Pierrot",
      image: "./images/4.jpg",
      date: "October 2022",
      pop: "5",
      source: "Sequel to BLEACH",
      story:
        "Was it all just a coincidence, or was it inevitable? Ichigo Kurosaki gained the powers of a Soul Reaper through a chance encounter. As a Substitute Soul Reaper, Ichigo became caught in the turmoil of the Soul Society, a place where deceased souls gather. But with help from his friends, Ichigo overcame every challenge to become even stronger. When new Soul Reapers and a new enemy appear in his hometown of Karakura, Ichigo jumps back into the battlefield with his Zanpakuto to help those in need. Meanwhile, the Soul Society is observing a sudden surge in the number of Hollows being destroyed in the World of the Living. They also receive separate reports of residents in the Rukon District having gone missing. Finally, the Seireitei, home of the Soul Reapers, comes under attack by a group calling themselves the Wandenreich. Led by Yhwach, the father of all Quincies, the Wandenreich declare war against the Soul Reapers with the following message: 'Five days from now, the Soul Society will be annihilated by the Wandenreich.' The history and truth kept hidden by the Soul Reapers for a thousand long years is finally brought to light. All things must come to an end-as Ichigo Kurosaki's final battle begins!action",
      genra: ["action", "adventure"],
      color: ["#EF5D5D"],
      flip: ["BLEACH_anim"],
      video: "https://youtu.be/1sygUhb8Q2Y",
    },
    {
      name: "Blue Lock",
      studio: "8-bit",
      image: "./images/5.jpg",
      date: "October 9, 2022",
      pop: "6",
      source: "Source • Manga",
      story:
        "After a disastrous defeat at the 2018 World Cup, Japan's team struggles to regroup. But what's missing? An absolute Ace Striker, who can guide them to the win. The Japan Football Union is hell-bent on creating a striker who hungers for goals and thirsts for victory, and who can be the decisive instrument in turning around a losing match...and to do so, they've gathered 300 of Japan's best and brightest youth players. Who will emerge to lead the team...and will they be able to out-muscle and out-ego everyone who stands in their way?actiondramasports",
      genra: ["action", "drama"],
      color: ["#3480EA"],
      flip: "ブルーロック",
      video: "https://youtu.be/g8iNMKef5MQ",
    },
    {
      name: "Bocchi the Rock!",
      studio: "CloverWorks",
      image: "./images/6.jpg",
      date: "October 2022",
      pop: "21",
      source: "Source • Manga",
      story:
        "Gotou Hitori is a high school girl who starting learning to playing the guitar because she dreams of being in a band, but she's so shy that she hasn't made a single friend. However, her dream might come true after she meets Ijichi Nijika, a girl who plays the drums and is looking for a new guitarist for her band.",
      genra: ["comedy", "music"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "ぼっち・ざ・ろっく",
      video: "https://youtu.be/Fp7lnCp_LW0",
    },
    {
      name: "Boku no Hero Academia 6",
      studio: "bones",
      image: "./images/7.jpg",
      date: "October 1, 2022",
      pop: "4",
      source: "Sequal to Boku no Hero Academia",
      story: "The sixth season of Boku no Hero Academia.",
      genra: ["action", "adventure"],
      color: ["#EF5D5D"],
      flip: "heroaca_a",
      video: "https://www.youtube.com/watch?v=mezyq2OX6TM",
    },
    {
      name: "C Danchi",
      studio: "Akatsuki",
      image: "./images/8.jpg",
      date: "October 2, 2022",
      pop: "",
      source: "Source • Original",
      story:
        "Housing Complex C centers around Kimi, who lives in a small, low-cost housing complex located in the seaside town of Kurosaki where trouble seems to follow her wherever she goes, and horrific incidents begin to occur. Is an ancient evil stalking the residents of Housing Complex C?",
      genra: ["horror", ""],
      color: ["#EF5D5D"],
      flip: "",
      video: "https://youtu.be/zhyGKfW8Sv4",
    },
    {
      name: "Chainsaw Man",
      studio: "MAPPA",
      image: "./images/9.jpg",
      date: "October 2022",
      pop: "1",
      source: "Source • Manga",
      story:
        "Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses with Pochita. One day, Denji is betrayed and killed. As his consciousness fades, he makes a contract with Pochita and gets revived as 'Chainsaw Man' — a man with a devil's heart.",
      genra: ["action", "comedy"],
      color: ["#8A2C0F"],
      flip: "チェンソーマン",
      video: "https://youtu.be/jk7QSGwupPA",
    },
    {
      name: "Cool Doji Danshi",
      studio: "Studio Pierrot",
      image: "./images/10.jpg",
      date: "October 2022",
      pop: "19",
      source: "Source • Manga",
      story:
        "Enter: a bunch of cool guys who look like they got that unapproachable swag. But let's be real—that's not the true them. They're just a bunch of dorks who've got the act down pat. So sit back, grab some popcorn and enjoy watching a bunch of goofy guys try to look cool all day every day.",
      genra: ["comedy", "slice of life"],
      color: ["#D3E7F3", "#28297B"],
      flip: "クールドジ男子",
      video: "https://www.youtube.com/watch?v=RHCLsZJscds",
    },
    {
      name: "Do It Yourself!!",
      studio: "PINE JAM",
      image: "./images/11.jpg",
      date: "October 2022",
      pop: "15",
      source: "Source • Original",
      story:
        "Building furniture and friendships have a lot in common. Intention, effort, and hard work are needed for both crafts. This is a story of girls in a DIY club building both as they carve out their futures. None of it comes easy, but that doesn’t stop any of ’em. Furniture, friendships, and the future—they’re building it all with their own hands!",
      genra: ["slice of life", ""],
      color: ["#FFF280", "#8A2C0F"],
      flip: "diyアニメ",
      video: "https://www.youtube.com/watch?v=lG0qqYjZI1I",
    },
    {
      name: "Eikyuu Shounen: Eternal Boys",
      studio: "LIDENFILMS",
      image: "./images/12.jpg",
      date: "October 2022",
      pop: "",
      source: "Source • Original",
      story:
        "'The Mature Idol Project' The latest project proposed by Manpuku Etertainment productions, in a bid to revive the company. Experienced in the successes and failures of the business world, 6 middle-aged men now face the many hurdles of age and physical ability, whilst pursuing their goal to become idols. In an effort to prove that old dogs can learn new tricks, and that you can still learn to shine no matter your age. These middle-aged men, and the end of their ropes, are taking a stand!",
      genra: ["comedy", ""],
      color: ["#6EC8F2", "#28297B"],
      flip: "エタボ",
      video: "",
    },
    {
      name: "Fumetsu no Anata e Season 2",
      studio: "Drive",
      image: "./images/13.jpg",
      date: "October 2022",
      pop: "12",
      source: "Sequal to Fumetsu no Anata e",
      story: "The second season of Fumetsu no Anata e.",
      genra: ["adventure", "drama"],
      color: ["#9263E9"],
      flip: "不滅のあなたへ",
      video: "",
    },
    {
      name: "Futoku no Guild",
      studio: "TNK",
      image: "./images/14.jpg",
      date: "October 2022",
      pop: "26",
      source: "Source • Manga",
      story:
        "Kikuru Madan, is a monster hunter with excellent performance, because of his particular job in the forest, but he decided to quit it because of fear wasting his own youth...",
      genra: ["action", "comedy"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "futoku_anime",
      video: "",
    },
    {
      name: "Fuufu Ijou, Koibito Miman.",
      studio: "studio MOTHER",
      image: "./images/15.jpg",
      date: "October 2022",
      pop: "17",
      source: "Source • Manga",
      story:
        "Third-year high school student Jirou Yakuin hoped to partner with Shiori Sakurazaka of the same class in the mandatory 'Couple Practical' course. In this practical, students must demonstrate that they have the necessary skillset to live with a partner of the opposite sex while presenting a certain level of harmony to the video surveillance that grades them. Unfortunately, random chance put his slightly subdued self into the practical with the person polar opposite to him, the gyaru Akari Watanabe. Akari on the other hand hoped to be paired with her crush Minami Tenjin. Their hopes are doubly dashed when they find out that Shiori and Minami are assigned together. Thus, they reluctantly decide to cooperate to reach the top ten, which would give them the right to exchange partners if both couples agree. To that end, Jirou steals Akari's first kiss without realizing what he'd done, while giving a hurried good-bye kiss...",
      genra: ["comedy", "drama"],
      color: ["#FFF280", "#8A2C0F"],
      flip: "ふうこいアニメ",
      video: "",
    },
    {
      name: "Golden Kamuy 4",
      studio: "Brain's Base",
      image: "./images/16.jpg",
      date: "October 2022",
      pop: "12",
      source: "Sequal to Golden Kamuy 3",
      story: "The fourth season of Golden Kamuy.",
      genra: ["action", "drama"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "ゴールデンカム",
      video: "",
    },
    {
      name: "IDOLiSH7: Third BEAT! Part 2",
      studio: "TROYCA",
      image: "./images/17.jpg",
      date: "October 2, 2022",
      pop: "",
      source: "Sequal to IDOLiSH7: Third BEAT!",
      story: "The second cour of the third season of IDOLiSH7.",
      genra: ["music", ""],
      color: ["#6EC8F2", "#28297B"],
      flip: "アニナナ",
      video: "",
    },
    {
      name: "Kage no Jitsuryokusha ni Naritakute!",
      studio: "Nexus",
      image: "./images/18.jpg",
      date: "October 2022",
      pop: "7",
      source: "Source • Lightnovil",
      story:
        "One big fat lie and a few twisted truths. Even in his past life, Cid's dream wasn't to become a protagonist or a final boss. He'd rather lie low as a minor character until it's prime time to reveal he's a mastermind...or at least, do the next best thing-pretend to be one! And now that he's been reborn into another world, he's ready to set the perfect conditions to live out his dreams to the fullest. Armed with his overactive imagination, Cid jokingly recruits members to his organization and makes up a whole backstory about an evil cult that they need to take down. Well, as luck would have it, these imaginary adversaries turn out to be the real deal-and everyone knows the truth but him!action come",
      genra: ["action", "comedy"],
      color: ["#3480EA"],
      flip: "陰の実力者",
      video: "",
    },
    {
      name: "KanColle: Itsuka Ano Umi de",
      studio: "ENGI",
      image: "./images/19.jpg",
      date: "October 2022",
      pop: "11",
      source: "Sequal to Kantai Collection: KanColle",
      story: "The long awaited sequel to Kantai Collection: KanColle.",
      genra: ["sci-fi", "action"],
      color: ["#FD354C"],
      flip: "艦これ",
      video: "",
    },
    {
      name: "Kidou Senshi Gundam: Suisei no Majo",
      studio: "Sunrise",
      image: "./images/20.jpg",
      date: "October 2022",
      pop: "20",
      source: "Sequal to Kidou Senshi Gundam ",
      story:
        "A.S. (Ad Stella) 122― An era when a multitude of corporations have entered space and built a huge economic system. A lone girl from the remote planet Mercury transfers to the Asticassia School of Technology, run by the Beneritt Group which dominates the mobile suit industry. Her name is Suletta Mercury. With a scarlet light burning in her pure heart, this girl walks step by step through a new world.",
      genra: ["sci-fi", "mech"],
      color: ["#9EBAFF", "#28297B"],
      flip: "水星の魔女",
      video: "",
    },
    {
      name: "Koukyuu no Karasu",
      studio: "Bandai Namco Pictures",
      image: "./images/21.jpg",
      date: "October 1, 2022",
      pop: "16",
      source: "Source • Light Novel",
      story:
        "Deep within the inner palace lives a special consort who does not serve the emperor despite her position as a consort. She is known as the Raven Consort. People who have seen her say she looks like an old women, while others say she looks like a young girl. Stories tell of her use of mysterious arts, and how she can take on any request, be it death curses or finding lost things. Koushun, the current emperor, goes to visit the Raven Consort with that intention. Without knowing that their fated meeting will become a taboo that will overturn history.",
      genra: ["mystry", ""],
      color: ["#FFF280", "#8A2C0F"],
      flip: "後宮の烏",
      video: "",
    },
    {
      name: "Mairimashita! Iruma-kun 3",
      studio: "Bandai Namco Pictures",
      image: "./images/22.jpg",
      date: "October 8, 2022",
      pop: "8",
      source: "Sequal to Mairimashita! Iruma-kun",
      story:
        "The third season of Mairimashita! Iruma-kun. This time it's the jungle! Human boy Suzuki Iruma becomes 'grandson' to the great demon Sullivan and begins attending demon school where 'Grandpa' serves as chair. Winning friends -- and rising in demon rank, too -- Iruma thrives in his new environment, overcoming the harrowing ordeals thrown his way! In the new season, further challenges await... it's harvest season, and time for the annual test where students wade into the expansive and extremely dangerous (!) jungle to compete for food!! Classmates become rivals, and what erupts is a gargantuan battle of brawn and wits?",
      genra: ["comedy", "fantasy"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "魔入りました入",
      video: "",
    },
    {
      name: "Megaton-kyuu Musashi 2nd Season",
      studio: "OLM",
      image: "./images/23.jpg",
      date: "October 7, 2022",
      pop: "",
      source: "Sequal to Megaton-kyuu Musashi",
      story: "The second season of Megaton-kyuu Musashi.",
      genra: ["mecha", ""],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "メガトン級ムサ",
      video: "",
    },
    {
      name: "Mob Psycho 100 III",
      studio: "bones",
      image: "./images/24.jpg",
      date: "October 6, 2022",
      pop: "3",
      source: "Sequal to",
      story: "The third season of Mob Psycho 100.",
      genra: ["action", "comedy"],
      color: ["#01C3D5"],
      flip: "モブサイコ100",
      video: "",
    },
    {
      name: "Mushikaburi-hime",
      studio: "MADHOUSE",
      image: "./images/25.jpg",
      date: "October 2022",
      pop: "24",
      source: "Source • Light Novel",
      story:
        "When book-loving Lady Elianna spots Prince Christopher—her betrothed in name only—consorting with another noble lady, she realizes the recent rumors must be true. The prince has someone he truly loves, which means the annulment of their engagement is both inevitable and fast-approaching. What she doesn’t realize is that this is merely a surface ripple—one of many where the truth runs deep, in a conspiracy surpassing her imagination!",
      genra: ["romance", ""],
      color: ["#6EC8F2", "#28297B"],
      flip: "虫かぶり姫",
      video: "",
    },
    {
      name: "Muv-Luv Alternative 2",
      studio: "FLAGSHIP LINE, Graphinica, Yumeta Company",
      image: "./images/26.jpg",
      date: "October 2022",
      pop: "",
      source: "Sequal to Muv-Luv Alternative",
      story: "The second season of Muv-Luv Alternative.",
      genra: ["action", "drama"],
      color: ["#4E5FB7"],
      flip: "マブラヴ",
      video: "",
    },
    {
      name: "Noumin Kanren no Skill Bakka Agetetara Naze ka Tsuyoku Natta.",
      studio: "studio A-CAT",
      image: "./images/27.jpg",
      date: "October 2022",
      pop: "22",
      source: "Source • Light Novel",
      story:
        "Al Wayne loves farming — and we don’t mean the video game sim. He wants to be a literal farmer, but in the process of improving his agriculture skills, he somehow winds up maxing out his overall character stats! He’s superpowered in the most unexpected of ways with abilities even the strongest of heroes would envy. Alas, all he wants is an idyllic farmer's life, but with demons and monsters invading the realm, Al may have to take up the mantle of hero just to keep his dreams from withering away!",
      genra: ["adventure", "fantasy"],
      color: ["#3480EA"],
      flip: "農民関連",
      video: "",
    },
    {
      name: "Poputepipikku",
      studio: "Space Neko Company, Kamikaze Douga",
      image: "./images/28.jpg",
      date: "October 2022",
      pop: "18",
      source: "Sequal to Poputepipikku",
      story: "The second season of Poputepipikku.",
      genra: ["comedy", ""],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "ポプテピピック",
      video: "",
    },
    {
      name: "Renai Flops",
      studio: "Passione",
      image: "./images/29.jpg",
      date: "October 2022",
      pop: "25",
      source: "Source • Original",
      story:
        "The story centers on Asahi Kashiwagi, a student who one morning runs into a series of unusual accidents the way to school — all in accordance with a vague television fortune he watched that morning, and all culminating with an unfortunate encounter with a girl. Coincidentally, all the girls he meets are new students or teachers at his school. Asahi's prior knowledge of the girls earns him the suspicion of Yoshio, a self-proclaimed 'friend of Asahi.' After school, he finds a love letter in his shoe locker, telling him to come to the cherry blossom tree behind school, again according to his morning fortune. Asahi heads to the cherry blossom tree to see what awaits him.",
      genra: ["comedy", "romance"],
      color: ["#E34F85"],
      flip: "恋愛フロップス",
      video: "",
    },
    {
      name: "Seiken Densetsu: Legend of Mana - The Teardrop Crystal",
      studio: "Graphinica, Yokohama Animation Lab",
      image: "./images/30.jpg",
      date: "October 8, 2022",
      pop: "",
      source: "Source • Video Game",
      story: "",
      genra: ["adventure", "fantasy"],
      color: ["#3480EA"],
      flip: "LoMアニメ",
      video: "",
    },
    {
      name: "Shinmai Renkinjutsushi no Tenpo Keiei",
      studio: "ENGI",
      image: "./images/31.jpg",
      date: "October 2022",
      pop: "29",
      source: "Source • Light Novel",
      story:
        "For a lonely orphan, there is almost only one career path to success. That is to get a national qualification as an alchemist. After graduating from the Royal Alchemist Training Academy, which requires nothing but ability, Sarasa is presented with the rights to a store by her master. After being sent off by her generous mentor, Sarasa sets off on her journey, dreaming of a slightly elegant life as an alchemist, but upon arrival, she is shocked to find that the countryside is even more rural than she had imagined. However, even in such a place, she has to manage a store somehow to make a living.",
      genra: ["fantacy", "slice of life"],
      color: ["#94FFA9", "#245313"],
      flip: "shinmai_renki",
      video: "",
    },
    {
      name: "Shinobi no Ittoki",
      studio: "TROYCA",
      image: "./images/32.jpg",
      date: "October 4, 2022",
      pop: "13",
      source: "Source • Original",
      story:
        "Ittoki Sakuraba was an ordinary student, until his life was turned upside down! He finds out that he is the 19th heir of the famous Iga Ninjas. The Iga must try to defend what is theirs from the Koga, a rivaling clan seeking to end Ittoki’s life. Ittoki is left with no choice but to become a shinobi that’s strong enough to not only protect himself, but also his village. Now a student at Kokuten Ninja Academy, a high school specializing in shinobi techniques, Ittoki learns the way of the modern-day ninja, equipped with high-tech suits and gadgets. Together with students from other villages, Ittoki clashes with the Koga in an attempt to end the rivalry once and for all.",
      genra: ["action", ""],
      color: ["#9CE53E", "#245313"],
      flip: "忍の一時",
      video: "",
    },
    {
      name: "SPY×FAMILY Part 2",
      studio: "Wit Studio, CloverWorks",
      image: "./images/33.jpg",
      date: "October 1, 2022",
      pop: "2",
      source: "Sequal to SPY×FAMILY",
      story: "The second half of SPYxFAMILY.",
      genra: ["action", "comedy"],
      color: ["#3480EA"],
      flip: "SPY_FAMILY",
      video: "",
    },
    {
      name: "Tensei Shitara Ken Deshita",
      studio: "C2C",
      image: "./images/34.jpg",
      date: "September 30, 2022",
      pop: "24",
      source: "Source • Light Novel",
      story:
        "Some isekai protagonists are reincarnated as powerful warriors or skilled wizards, but our protagonist was reborn in another life as a sentient sword! He’s taken up by Fran, a desperate girl fleeing evil-doers intent on selling her into slavery. With her new weapon’s help and guidance, she’s able to strike down her captors and secure her freedom. Together, this unconventional master-student duo embark on an epic journey to liberate those in need and exact justice on the cruel of heart.",
      genra: ["action", "adventure"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "転生したら剣で",
      video: "",
    },
    {
      name: "Uchi no Shishou wa Shippo ga Nai",
      studio: "LIDENFILMS",
      image: "./images/35.jpg",
      date: "September 2022",
      pop: "28",
      source: "Source • Manga",
      story:
        "In Japan's Taishou era (1912–1926), Mameda is a shape-shifting tanuki girl who dreams of becoming human. Mame transforms her outward appearance into a pretty raven-haired human girl and heads to the bustling city of Osaka. However, people instantly see through Mameda's guise, and one beautiful woman ruthlessly says to the dejected Mameda, 'Go back where you came from.'' As it turns out, that woman named Bunko is herself a supernatural creature who transformed herself into a rakugo (comic storytelling) storyteller. Mameda begs Bunko to become her master and teach her the ways of playing a human.",
      genra: ["comedy", "fantasy"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "しっぽな",
      video: "",
    },
    {
      name: "Urusei Yatsura (2022)",
      studio: "David Production",
      image: "./images/36.jpg",
      date: "October 2022",
      pop: "9",
      source: "Source • Manga",
      story:
        "Tokyo. Tomobiki Town. Lum, the gorgeous daughter of an invading race of Oni Aliens is smitten with High School student Ataru Moroboshi. A dedicated womanizer, Ataru is unfazed by Lum’s fierce electric shock attacks and continues his daily hunt for pretty girls. With a host of other unique characters, including classmate Shinobu, elegant shrine maiden Sakura, Lum’s best friend’s Oyuki, Benten and Ran, Buddhist Monk Cherry, Ten, the little brat, heir to a wealthy family Shuutaro Mendou and the secretly female beauty Ryunosuke… A classic slapstick love comedy where anything goes! Note: A new adaption of the manga of the same name by Rumiko Takahashi.",
      genra: ["comedy", "romance"],
      color: ["#9EBAFF", "#28297B"],
      flip: "うる星やつら",
      video: "",
    },
    {
      name: "Uzaki-chan wa Asobitai! ω",
      studio: "ENGI",
      image: "./images/37.jpg",
      date: "2022",
      pop: "19",
      source: "Sequal to Uzaki-chan wa Asobitai!",
      story: "The second season of Uzaki-chan wa Asobitai!.",
      genra: ["comedy", "ecchi"],
      color: ["#94FFA9", "#245313"],
      flip: "宇崎ちゃん",
      video: "",
    },
    {
      name: "VAZZROCK THE ANIMATION",
      studio: "PRA",
      image: "./images/38.jpg",
      date: "October 2022",
      pop: "",
      source: "Source • Original",
      story: "",
      genra: ["music", ""],
      color: ["#D3E7F3", "#1B4964"],
      flip: "バズロ",
      video: "",
    },
    {
      name: "Yama no Susume: Next Summit",
      studio: "8-bit",
      image: "./images/39.jpg",
      date: "October 5, 2022",
      pop: "27",
      source: "Sequal to Yama no Susume",
      story: "The fourth season of Yama no Susume.",
      genra: ["adventure", "comedy"],
      color: ["#3480EA"],
      flip: "ヤマノススメ",
      video: "",
    },
    {
      name: "Yowamushi Pedal: LIMIT BREAK",
      studio: "TMS Entertainment",
      image: "./images/40.jpg",
      date: "October 2022",
      pop: "30",
      source: "Sequal to Yowamushi Pedal",
      story: "The fifth season of Yowamushi Pedal.",
      genra: ["comedy", "drama"],
      color: ["#EBB62D", "#8A2C0F"],
      flip: "yp_anime",
      video: "",
    },
    {
      name: "Yuusha Party wo Tsuihou Sareta Beast Tamer, Saikyoushu no Nekomimi Shoujo to Deau",
      studio: "EMT Squared",
      image: "./images/41.jpg",
      date: "October 2022",
      pop: "23",
      source: "Source • Light Novel",
      story:
        "Because Rain was a weak and simple beast tamer, he was expelled from the hero's group but that didn't stop his desire to be an adventurer. By taking simple quests afterwards he has a destined encounter with a strong cat girl.",
      genra: ["adventure", "fantasy"],
      color: ["#6EC8F2", "#28297B"],
      flip: "ビステマ",
      video: "",
    },
  ],
  [
    {
      name: "Aru Asa Dummy Head Mic ni Natteita Ore-kun no Jinsei",
      studio: "EKACHI EPILKA, INDIVISION",
      image: "./images/42.jpg",
      date: "October 2022",
      pop: "3",
      source: "Source • Original",
      story:
        "The slapstick comedy revolves around a protagonist who was reincarnated into a dummy head microphone (a microphone embedded in a fake human head to faithfully record the aural ambience). That dummy head microphone happens to be used by Yuri and other high school girls in an ASMR club, who have their sights set on the 'ASMR Koushien' high school championships. (ASMR or Autonomous Sensory Meridian Response is the nerve-tingling or relaxing sensation one gets in response to stimuli such as certain sounds or sights.)",
      genra: ["comedy", "slice of life"],
      color: ["#EBB62D"],
      flip: "俺クン",
      video: "",
    },
    {
      name: "Peter Grill to Kenja no Jikan: Super Extra",
      studio: "Seven, WolfsBane",
      image: "./images/43.jpg",
      date: "October 2022",
      pop: "1",
      source: "Sequal to Peter Grill to Kenja no Jikan",
      story:
        "The second season of Peter Grill to Kenja no Jikan. Peter Grill is back and ready for action! Between quelling a goblin incursion, improving trade negotiations with the dwarves and placating a watchful sister who might just go berserk to keep him in line, Peter has his work cut out for him. He’s the most sought-after hero in the land…and that’s before counting the myriad woman interested in his “other” talents. It will take every last scrap of Peter’s willpower to keep his focus on heroing in another raunchy season of Peter Grill and the Philosopher’s Time - Super Extra!",
      genra: ["comedy", "ecchi"],
      color: ["#EF5D5D"],
      flip: "賢者タイムアニ",
      video: "",
    },
    {
      name: "PUI PUI Molcar: DRIVING SCHOOL",
      studio: "",
      image: "./images/44.jpg",
      date: "October 2022",
      pop: "2",
      source: "sequal to PUI PUI Molcar",
      story: "",
      genra: ["comedy", ""],
      color: ["#EBB62D"],
      flip: "モルカー",
      video: "",
    },
    {
      name: "Reiwa no Di Gi Charat",
      studio: "LIDENFILMS",
      image: "./images/45.jpg",
      date: "October 2022",
      pop: "4",
      source: "Source • Original",
      story:
        "Mini anime to celebrate the Di Gi Charat franchise's 24th anniversary.",
      genra: ["", ""],
      color: [],
      flip: "令和のデ・ジ・",
      video: "",
    },
  ],
  [
    {
      name: "Hoshi no Samidare",
      studio: "NAZ",
      image: "./images/46.jpg",
      date: "October 2022",
      pop: "22",
      source: "Source • Manga",
      story:
        "One day, unremarkable college student Yuuhi Amamiya meets a talking lizard who asks for his help saving Earth from a crisis. Before he can refuse, Yuuhi is turned into a member of the Beast Knights and given a ring that gives him the psychic power “domain control.” He is then immediately attacked by an enemy! But just as all seems lost, he’s saved by the girl next door, Samidare. But it turns out Samidare isn’t really a savior of any kind… she’s actually a demon lord who wants to conquer Earth! Drawn to her absurd strength and evil charms, Yuuhi becomes her devoted servant and acts to support her wicked schemes.",
      genra: ["comedy", "action"],
      color: ["#3480EA"],
      flip: "惑星のさみだれ",
      video: "",
    },
    {
      name: "Utawarerumono: Futari no Hakuoro",
      studio: "White Fox",
      image: "./images/47.jpg",
      date: "October 2022",
      pop: "",
      source: "Sequal to Utawarerumono",
      story:
        "Chaos has taken hold of the land as a conniving general has unlawfully seized the throne of the mighty Yamato Empire. The only ones that stand in his way are a couple of familiar faces who must rally different kingdoms together and fight against the powerful Imperial army.",
      genra: ["action", "drama"],
      color: ["#EBB62D"],
      flip: "うたわれ",
      video: "",
    },
  ],
];
